<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kota = [
            ['provinsi_id' => 1, 'kota' => 'KABUPATEN SIMEULUE'],
            ['provinsi_id' => 1, 'kota' => 'KABUPATEN ACEH SINGKIL'],
            ['provinsi_id' => 1, 'kota' => 'KABUPATEN ACEH SELATAN'],
            ['provinsi_id' => 1, 'kota' => 'KOTA LANGSA'],
            ['provinsi_id' => 1, 'kota' => 'KOTA LHOKSEUMAWE'],
            ['provinsi_id' => 1, 'kota' => 'KOTA SUBULUSSALAM'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN NIAS'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN MANDAILING NATAL'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN TAPANULI SELATAN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN TAPANULI TENGAH'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN TAPANULI UTARA'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN TOBA SAMOSIR'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN LABUHAN BATU'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN ASAHAN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN SIMALUNGUN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN DAIRI'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN KARO'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN DELI SERDANG'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN LANGKAT'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN NIAS SELATAN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN HUMBANG HASUNDUTAN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN PAKPAK BHARAT'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN SAMOSIR'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN SERDANG BEDAGAI'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN BATU BARA'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN PADANG LAWAS UTARA'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN PADANG LAWAS'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN LABUHAN BATU SELATAN'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN LABUHAN BATU UTARA'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN NIAS UTARA'],
            ['provinsi_id' => 2, 'kota' => 'KABUPATEN NIAS BARAT'],
            ['provinsi_id' => 2, 'kota' => 'KOTA SIBOLGA'],
            ['provinsi_id' => 2, 'kota' => 'KOTA TANJUNG BALAI'],
            ['provinsi_id' => 2, 'kota' => 'KOTA PEMATANG SIANTAR'],
            ['provinsi_id' => 2, 'kota' => 'KOTA TEBING TINGGI'],
            ['provinsi_id' => 2, 'kota' => 'KOTA MEDAN'],
            ['provinsi_id' => 2, 'kota' => 'KOTA BINJAI'],
            ['provinsi_id' => 2, 'kota' => 'KOTA PADANGSIDIMPUAN'],
            ['provinsi_id' => 2, 'kota' => 'KOTA GUNUNGSITOLI'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN KEPULAUAN MENTAWAI'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN PESISIR SELATAN'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN SOLOK'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN SIJUNJUNG'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN TANAH DATAR'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN PADANG PARIAMAN'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN AGAM'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN LIMA PULUH KOTA'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN PASAMAN'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN SOLOK SELATAN'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN DHARMASRAYA'],
            ['provinsi_id' => 3, 'kota' => 'KABUPATEN PASAMAN BARAT'],
            ['provinsi_id' => 3, 'kota' => 'KOTA PADANG'],
            ['provinsi_id' => 3, 'kota' => 'KOTA SOLOK'],
            ['provinsi_id' => 3, 'kota' => 'KOTA SAWAH LUNTO'],
            ['provinsi_id' => 3, 'kota' => 'KOTA PADANG PANJANG'],
            ['provinsi_id' => 3, 'kota' => 'KOTA BUKITTINGGI'],
            ['provinsi_id' => 3, 'kota' => 'KOTA PAYAKUMBUH'],
            ['provinsi_id' => 3, 'kota' => 'KOTA PARIAMAN'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN KUANTAN SINGINGI'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN INDRAGIRI HULU'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN INDRAGIRI HILIR'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN PELALAWAN'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN S I A K'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN KAMPAR'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN ROKAN HULU'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN BENGKALIS'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN ROKAN HILIR'],
            ['provinsi_id' => 4, 'kota' => 'KABUPATEN KEPULAUAN MERANTI'],
            ['provinsi_id' => 4, 'kota' => 'KOTA PEKANBARU'],
            ['provinsi_id' => 4, 'kota' => 'KOTA D U M A I'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN KERINCI'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN MERANGIN'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN SAROLANGUN'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN BATANG HARI'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN MUARO JAMBI'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN TANJUNG JABUNG BARAT'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN TEBO'],
            ['provinsi_id' => 5, 'kota' => 'KABUPATEN BUNGO'],
            ['provinsi_id' => 5, 'kota' => 'KOTA JAMBI'],
            ['provinsi_id' => 5, 'kota' => 'KOTA SUNGAI PENUH'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN OGAN KOMERING ULU'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN OGAN KOMERING ILIR'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN MUARA ENIM'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN LAHAT'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN MUSI RAWAS'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN MUSI BANYUASIN'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN BANYU ASIN'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN OGAN ILIR'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN EMPAT LAWANG'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
            ['provinsi_id' => 6, 'kota' => 'KABUPATEN MUSI RAWAS UTARA'],
            ['provinsi_id' => 6, 'kota' => 'KOTA PALEMBANG'],
            ['provinsi_id' => 6, 'kota' => 'KOTA PRABUMULIH'],
            ['provinsi_id' => 6, 'kota' => 'KOTA PAGAR ALAM'],
            ['provinsi_id' => 6, 'kota' => 'KOTA LUBUKLINGGAU'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN BENGKULU SELATAN'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN REJANG LEBONG'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN BENGKULU UTARA'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN KAUR'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN SELUMA'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN MUKOMUKO'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN LEBONG'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN KEPAHIANG'],
            ['provinsi_id' => 7, 'kota' => 'KABUPATEN BENGKULU TENGAH'],
            ['provinsi_id' => 7, 'kota' => 'KOTA BENGKULU'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN LAMPUNG BARAT'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN TANGGAMUS'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN LAMPUNG SELATAN'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN LAMPUNG TIMUR'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN LAMPUNG TENGAH'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN LAMPUNG UTARA'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN WAY KANAN'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN TULANGBAWANG'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN PESAWARAN'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN PRINGSEWU'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN MESUJI'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN TULANG BAWANG BARAT'],
            ['provinsi_id' => 8, 'kota' => 'KABUPATEN PESISIR BARAT'],
            ['provinsi_id' => 8, 'kota' => 'KOTA BANDAR LAMPUNG'],
            ['provinsi_id' => 8, 'kota' => 'KOTA METRO'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BANGKA'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BELITUNG'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BANGKA BARAT'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BANGKA TENGAH'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BANGKA SELATAN'],
            ['provinsi_id' => 9, 'kota' => 'KABUPATEN BELITUNG TIMUR'],
            ['provinsi_id' => 9, 'kota' => 'KOTA PANGKAL PINANG'],
            ['provinsi_id' => 10, 'kota' => 'KABUPATEN KARIMUN'],
            ['provinsi_id' => 10, 'kota' => 'KABUPATEN BINTAN'],
            ['provinsi_id' => 10, 'kota' => 'KABUPATEN NATUNA'],
            ['provinsi_id' => 10, 'kota' => 'KABUPATEN LINGGA'],
            ['provinsi_id' => 10, 'kota' => 'KABUPATEN KEPULAUAN ANAMBAS'],
            ['provinsi_id' => 10, 'kota' => 'KOTA BATAM'],
            ['provinsi_id' => 10, 'kota' => 'KOTA TANJUNG PINANG'],
            ['provinsi_id' => 11, 'kota' => 'KABUPATEN KEPULAUAN SERIBU'],
            ['provinsi_id' => 11, 'kota' => 'KOTA JAKARTA SELATAN'],
            ['provinsi_id' => 11, 'kota' => 'KOTA JAKARTA TIMUR'],
            ['provinsi_id' => 11, 'kota' => 'KOTA JAKARTA PUSAT'],
            ['provinsi_id' => 11, 'kota' => 'KOTA JAKARTA BARAT'],
            ['provinsi_id' => 11, 'kota' => 'KOTA JAKARTA UTARA'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN BOGOR'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN SUKABUMI'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN CIANJUR'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN BANDUNG'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN GARUT'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN TASIKMALAYA'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN CIAMIS'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN KUNINGAN'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN CIREBON'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN MAJALENGKA'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN SUMEDANG'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN INDRAMAYU'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN SUBANG'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN PURWAKARTA'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN KARAWANG'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN BEKASI'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN BANDUNG BARAT'],
            ['provinsi_id' => 12, 'kota' => 'KABUPATEN PANGANDARAN'],
            ['provinsi_id' => 12, 'kota' => 'KOTA BOGOR'],
            ['provinsi_id' => 12, 'kota' => 'KOTA SUKABUMI'],
            ['provinsi_id' => 12, 'kota' => 'KOTA BANDUNG'],
            ['provinsi_id' => 12, 'kota' => 'KOTA CIREBON'],
            ['provinsi_id' => 12, 'kota' => 'KOTA BEKASI'],
            ['provinsi_id' => 12, 'kota' => 'KOTA DEPOK'],
            ['provinsi_id' => 12, 'kota' => 'KOTA CIMAHI'],
            ['provinsi_id' => 12, 'kota' => 'KOTA TASIKMALAYA'],
            ['provinsi_id' => 12, 'kota' => 'KOTA BANJAR'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN CILACAP'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BANYUMAS'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN PURBALINGGA'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BANJARNEGARA'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN KEBUMEN'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN PURWOREJO'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN WONOSOBO'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN MAGELANG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BOYOLALI'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN KLATEN'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN SUKOHARJO'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN WONOGIRI'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN KARANGANYAR'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN SRAGEN'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN GROBOGAN'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BLORA'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN REMBANG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN PATI'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN KUDUS'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN JEPARA'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN DEMAK'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN SEMARANG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN TEMANGGUNG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN KENDAL'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BATANG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN PEKALONGAN'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN PEMALANG'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN TEGAL'],
            ['provinsi_id' => 13, 'kota' => 'KABUPATEN BREBES'],
            ['provinsi_id' => 13, 'kota' => 'KOTA MAGELANG'],
            ['provinsi_id' => 13, 'kota' => 'KOTA SURAKARTA'],
            ['provinsi_id' => 13, 'kota' => 'KOTA SALATIGA'],
            ['provinsi_id' => 13, 'kota' => 'KOTA SEMARANG'],
            ['provinsi_id' => 13, 'kota' => 'KOTA PEKALONGAN'],
            ['provinsi_id' => 13, 'kota' => 'KOTA TEGAL'],
            ['provinsi_id' => 14, 'kota' => 'KABUPATEN KULON PROGO'],
            ['provinsi_id' => 14, 'kota' => 'KABUPATEN BANTUL'],
            ['provinsi_id' => 14, 'kota' => 'KABUPATEN GUNUNG KIDUL'],
            ['provinsi_id' => 14, 'kota' => 'KABUPATEN SLEMAN'],
            ['provinsi_id' => 14, 'kota' => 'KOTA YOGYAKARTA'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN PACITAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN PONOROGO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN TRENGGALEK'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN TULUNGAGUNG'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN BLITAR'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN KEDIRI'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN MALANG'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN LUMAJANG'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN JEMBER'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN BANYUWANGI'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN BONDOWOSO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN SITUBONDO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN PROBOLINGGO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN PASURUAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN SIDOARJO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN MOJOKERTO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN JOMBANG'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN NGANJUK'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN MADIUN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN MAGETAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN NGAWI'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN BOJONEGORO'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN TUBAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN LAMONGAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN GRESIK'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN BANGKALAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN SAMPANG'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN PAMEKASAN'],
            ['provinsi_id' => 15, 'kota' => 'KABUPATEN SUMENEP'],
            ['provinsi_id' => 15, 'kota' => 'KOTA KEDIRI'],
            ['provinsi_id' => 15, 'kota' => 'KOTA BLITAR'],
            ['provinsi_id' => 15, 'kota' => 'KOTA MALANG'],
            ['provinsi_id' => 15, 'kota' => 'KOTA PROBOLINGGO'],
            ['provinsi_id' => 15, 'kota' => 'KOTA PASURUAN'],
            ['provinsi_id' => 15, 'kota' => 'KOTA MOJOKERTO'],
            ['provinsi_id' => 15, 'kota' => 'KOTA MADIUN'],
            ['provinsi_id' => 15, 'kota' => 'KOTA SURABAYA'],
            ['provinsi_id' => 15, 'kota' => 'KOTA BATU'],
            ['provinsi_id' => 16, 'kota' => 'KABUPATEN PANDEGLANG'],
            ['provinsi_id' => 16, 'kota' => 'KABUPATEN LEBAK'],
            ['provinsi_id' => 16, 'kota' => 'KABUPATEN TANGERANG'],
            ['provinsi_id' => 16, 'kota' => 'KABUPATEN SERANG'],
            ['provinsi_id' => 16, 'kota' => 'KOTA TANGERANG'],
            ['provinsi_id' => 16, 'kota' => 'KOTA CILEGON'],
            ['provinsi_id' => 16, 'kota' => 'KOTA SERANG'],
            ['provinsi_id' => 16, 'kota' => 'KOTA TANGERANG SELATAN'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN JEMBRANA'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN TABANAN'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN BADUNG'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN GIANYAR'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN KLUNGKUNG'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN BANGLI'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN KARANG ASEM'],
            ['provinsi_id' => 17, 'kota' => 'KABUPATEN BULELENG'],
            ['provinsi_id' => 17, 'kota' => 'KOTA DENPASAR'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN LOMBOK BARAT'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN LOMBOK TENGAH'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN LOMBOK TIMUR'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN SUMBAWA'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN DOMPU'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN BIMA'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN SUMBAWA BARAT'],
            ['provinsi_id' => 18, 'kota' => 'KABUPATEN LOMBOK UTARA'],
            ['provinsi_id' => 18, 'kota' => 'KOTA MATARAM'],
            ['provinsi_id' => 18, 'kota' => 'KOTA BIMA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SUMBA BARAT'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SUMBA TIMUR'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN KUPANG'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN TIMOR TENGAH SELATAN'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN TIMOR TENGAH UTARA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN BELU'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN ALOR'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN LEMBATA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN FLORES TIMUR'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SIKKA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN ENDE'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN NGADA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN MANGGARAI'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN ROTE NDAO'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN MANGGARAI BARAT'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SUMBA TENGAH'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SUMBA BARAT DAYA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN NAGEKEO'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN MANGGARAI TIMUR'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN SABU RAIJUA'],
            ['provinsi_id' => 19, 'kota' => 'KABUPATEN MALAKA'],
            ['provinsi_id' => 19, 'kota' => 'KOTA KUPANG'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN SAMBAS'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN BENGKAYANG'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN LANDAK'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN MEMPAWAH'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN SANGGAU'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN KETAPANG'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN SINTANG'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN KAPUAS HULU'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN SEKADAU'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN MELAWI'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN KAYONG UTARA'],
            ['provinsi_id' => 20, 'kota' => 'KABUPATEN KUBU RAYA'],
            ['provinsi_id' => 20, 'kota' => 'KOTA PONTIANAK'],
            ['provinsi_id' => 20, 'kota' => 'KOTA SINGKAWANG'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN KOTAWARINGIN BARAT'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN KOTAWARINGIN TIMUR'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN KAPUAS'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN BARITO SELATAN'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN BARITO UTARA'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN SUKAMARA'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN LAMANDAU'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN SERUYAN'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN KATINGAN'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN PULANG PISAU'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN GUNUNG MAS'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN BARITO TIMUR'],
            ['provinsi_id' => 21, 'kota' => 'KABUPATEN MURUNG RAYA'],
            ['provinsi_id' => 21, 'kota' => 'KOTA PALANGKA RAYA'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN TANAH LAUT'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN KOTA BARU'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN BANJAR'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN BARITO KUALA'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN TAPIN'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN HULU SUNGAI SELATAN'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN HULU SUNGAI TENGAH'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN HULU SUNGAI UTARA'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN TABALONG'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN TANAH BUMBU'],
            ['provinsi_id' => 22, 'kota' => 'KABUPATEN BALANGAN'],
            ['provinsi_id' => 22, 'kota' => 'KOTA BANJARMASIN'],
            ['provinsi_id' => 22, 'kota' => 'KOTA BANJAR BARU'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN PASER'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN KUTAI BARAT'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN KUTAI KARTANEGARA'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN KUTAI TIMUR'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN BERAU'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN PENAJAM PASER UTARA'],
            ['provinsi_id' => 23, 'kota' => 'KABUPATEN MAHAKAM HULU'],
            ['provinsi_id' => 23, 'kota' => 'KOTA BALIKPAPAN'],
            ['provinsi_id' => 23, 'kota' => 'KOTA SAMARINDA'],
            ['provinsi_id' => 23, 'kota' => 'KOTA BONTANG'],
            ['provinsi_id' => 24, 'kota' => 'KABUPATEN MALINAU'],
            ['provinsi_id' => 24, 'kota' => 'KABUPATEN BULUNGAN'],
            ['provinsi_id' => 24, 'kota' => 'KABUPATEN TANA TIDUNG'],
            ['provinsi_id' => 24, 'kota' => 'KABUPATEN NUNUKAN'],
            ['provinsi_id' => 24, 'kota' => 'KOTA TARAKAN'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN BOLAANG MONGONDOW'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN MINAHASA'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN KEPULAUAN SANGIHE'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN KEPULAUAN TALAUD'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN MINAHASA SELATAN'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN MINAHASA UTARA'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN MINAHASA TENGGARA'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
            ['provinsi_id' => 25, 'kota' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
            ['provinsi_id' => 25, 'kota' => 'KOTA MANADO'],
            ['provinsi_id' => 25, 'kota' => 'KOTA BITUNG'],
            ['provinsi_id' => 25, 'kota' => 'KOTA TOMOHON'],
            ['provinsi_id' => 25, 'kota' => 'KOTA KOTAMOBAGU'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN BANGGAI KEPULAUAN'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN BANGGAI'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN MOROWALI'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN POSO'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN DONGGALA'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN TOLI-TOLI'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN BUOL'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN PARIGI MOUTONG'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN TOJO UNA-UNA'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN SIGI'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN BANGGAI LAUT'],
            ['provinsi_id' => 26, 'kota' => 'KABUPATEN MOROWALI UTARA'],
            ['provinsi_id' => 26, 'kota' => 'KOTA PALU'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN KEPULAUAN SELAYAR'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN BULUKUMBA'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN BANTAENG'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN JENEPONTO'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN TAKALAR'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN GOWA'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN SINJAI'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN MAROS'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN BARRU'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN BONE'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN SOPPENG'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN WAJO'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN SIDENRENG RAPPANG'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN PINRANG'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN ENREKANG'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN LUWU'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN TANA TORAJA'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN LUWU UTARA'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN LUWU TIMUR'],
            ['provinsi_id' => 27, 'kota' => 'KABUPATEN TORAJA UTARA'],
            ['provinsi_id' => 27, 'kota' => 'KOTA MAKASSAR'],
            ['provinsi_id' => 27, 'kota' => 'KOTA PAREPARE'],
            ['provinsi_id' => 27, 'kota' => 'KOTA PALOPO'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN BUTON'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN MUNA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KONAWE'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KOLAKA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KONAWE SELATAN'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN BOMBANA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN WAKATOBI'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KOLAKA UTARA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN BUTON UTARA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KONAWE UTARA'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KOLAKA TIMUR'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN KONAWE KEPULAUAN'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN MUNA BARAT'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN BUTON TENGAH'],
            ['provinsi_id' => 28, 'kota' => 'KABUPATEN BUTON SELATAN'],
            ['provinsi_id' => 28, 'kota' => 'KOTA KENDARI'],
            ['provinsi_id' => 28, 'kota' => 'KOTA BAUBAU'],
            ['provinsi_id' => 29, 'kota' => 'KABUPATEN BOALEMO'],
            ['provinsi_id' => 29, 'kota' => 'KABUPATEN GORONTALO'],
            ['provinsi_id' => 29, 'kota' => 'KABUPATEN POHUWATO'],
            ['provinsi_id' => 29, 'kota' => 'KABUPATEN BONE BOLANGO'],
            ['provinsi_id' => 29, 'kota' => 'KABUPATEN GORONTALO UTARA'],
            ['provinsi_id' => 29, 'kota' => 'KOTA GORONTALO'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN MAJENE'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN POLEWALI MANDAR'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN MAMASA'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN MAMUJU'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN MAMUJU UTARA'],
            ['provinsi_id' => 30, 'kota' => 'KABUPATEN MAMUJU TENGAH'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN MALUKU TENGGARA BARAT'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN MALUKU TENGGARA'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN MALUKU TENGAH'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN BURU'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN KEPULAUAN ARU'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN SERAM BAGIAN BARAT'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN SERAM BAGIAN TIMUR'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN MALUKU BARAT DAYA'],
            ['provinsi_id' => 31, 'kota' => 'KABUPATEN BURU SELATAN'],
            ['provinsi_id' => 31, 'kota' => 'KOTA AMBON'],
            ['provinsi_id' => 31, 'kota' => 'KOTA TUAL'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN HALMAHERA BARAT'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN HALMAHERA TENGAH'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN KEPULAUAN SULA'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN HALMAHERA SELATAN'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN HALMAHERA UTARA'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN HALMAHERA TIMUR'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN PULAU MOROTAI'],
            ['provinsi_id' => 32, 'kota' => 'KABUPATEN PULAU TALIABU'],
            ['provinsi_id' => 32, 'kota' => 'KOTA TERNATE'],
            ['provinsi_id' => 32, 'kota' => 'KOTA TIDORE KEPULAUAN'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN FAKFAK'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN KAIMANA'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN TELUK WONDAMA'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN TELUK BINTUNI'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN MANOKWARI'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN SORONG SELATAN'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN SORONG'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN RAJA AMPAT'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN TAMBRAUW'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN MAYBRAT'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN MANOKWARI SELATAN'],
            ['provinsi_id' => 33, 'kota' => 'KABUPATEN PEGUNUNGAN ARFAK'],
            ['provinsi_id' => 33, 'kota' => 'KOTA SORONG'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN MERAUKE'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN JAYAWIJAYA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN JAYAPURA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN NABIRE'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN KEPULAUAN YAPEN'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN BIAK NUMFOR'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN PANIAI'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN PUNCAK JAYA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN MIMIKA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN BOVEN DIGOEL'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN MAPPI'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN ASMAT'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN YAHUKIMO'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN PEGUNUNGAN BINTANG'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN TOLIKARA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN SARMI'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN KEEROM'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN WAROPEN'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN SUPIORI'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN MAMBERAMO RAYA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN NDUGA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN LANNY JAYA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN MAMBERAMO TENGAH'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN YALIMO'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN PUNCAK'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN DOGIYAI'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN INTAN JAYA'],
            ['provinsi_id' => 34, 'kota' => 'KABUPATEN DEIYAI'],
            ['provinsi_id' => 34, 'kota' => 'KOTA JAYAPURA'],
        ];
        DB::table('kotas')->insert($kota);

    }
}
